### ISSUE TITLE
Не грузит длинные видео?

### ISSUE THREAD

**Issue by GitOperki** [lowfc/boosty_downloader#3]
Из 68 видео скачал автоматически только 3. Те, которые самые короткие (по 8 мин). Остальные более длинные (по 2 часа) не качает, выдает:
[TimeoutError] App stopped
Press enter to exit...

Но вроде можно взять ссылку на каждое отдельное видео, которая выдается в командной строке при работе программы и вставив в браузер скачать вручную по 1 видео по порядку.

2024-08-14 16:19:39,740 [INFO] downloading file https://vd485.mycdn.me/? ... 7723 <<  Вот эту ссылку
2024-08-14 16:19:39,742 [INFO] will save file: F:\boosty_dumps ...

**Comment by lowfc** [comment]
Исправлено в [1.0.2](https://github.com/lowfc/boosty_downloader/releases/tag/1.0.2)
