### ISSUE TITLE
Возможность скачивать не весь контент пользователя, а единичный

### ISSUE THREAD

**Issue by elite-nick** [lowfc/boosty_downloader#5]
Программа замечательная, спасибо :)

Есть вопрос - возможна ли доработка у этой программы скачки не всего контента пользователя, а определенного поста с видео/картинкой?

**Comment by lowfc** [comment]
Привет! Было в планах. Думаю, займусь в этом месяце =)

**Comment by lowfc** [comment]
Фича появилась в [релизе 1.0.3](https://github.com/lowfc/boosty_downloader/releases/tag/1.0.3)

Что бы скачать определенный пост, установи в конфиге `storage_type: post` и запускай приложение с параметром -p <id поста>, например:

`./boosty_downloader_1.0.3.exe -p e87f6e1b-67ab-4fd0-9633-f8efe4ad1990`
