### ISSUE TITLE
в заголовках запроса нет Authorization

### ISSUE THREAD

**Issue by strannick-ru** [lowfc/boosty_downloader#9]
Добрый день.

Проверил в разных браузерах, посмотрел на все запросы с типом POST.
Cookie в заголовках хапроса есть, а Authorization отсутствуют.

Может ли такое быть, если я использую авторизацию через социальные сети (ВК в моём случае)?

**Comment by strannick-ru** [comment]
вопрос снят.
проверил снова и всё нашлось.
как я не увидел этот заголовок в прошлый раз — вопрос интересный, но к теме не относящийся.

**Comment by vasyan35** [comment]
> вопрос снят. проверил снова и всё нашлось. как я не увидел этот заголовок в прошлый раз — вопрос интересный, но к теме не относящийся.

А где найти запрос POST, я его найти не могу, подскажите пожалуйста, может скрином каким нибудь.

**Comment by strannick-ru** [comment]
![изображение](https://github.com/user-attachments/assets/e3f154f1-bd15-4d64-9989-c56d7e0b4725)
нажимаете в браузере F12, выбираете вкладку "сеть" (я пользуюсь FF, в Chrome всё аналогично) и всё.

на главной boosty заголовка Authorization нет, но вот если зайти на пост с видео — там он появляется.

**Comment by vasyan35** [comment]
> > вопрос снят. проверил снова и всё нашлось. как я не увидел этот заголовок в прошлый раз — вопрос интересный, но к теме не относящийся.
> 
> А где найти запрос POST, я его найти не могу, подскажите пожалуйста, может скрином каким нибудь.
> 
> Update: нашел где POST, теперь тоже не могу найти Authorization. Вы где нашли? ![Снимок экрана 2024-12-18 211624](https://private-user-images.githubusercontent.com/191893933/397009828-bd7d831a-3744-4590-b2d4-d38274e23af2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NDE3OTIsIm5iZiI6MTczNDU0MTQ5MiwicGF0aCI6Ii8xOTE4OTM5MzMvMzk3MDA5ODI4LWJkN2Q4MzFhLTM3NDQtNDU5MC1iMmQ0LWQzODI3NGUyM2FmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQxNzA0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjBlMDVlZTdhM2Q4ZTI2MWI4NWZlN2I4ZjNkY2FlYjRkYTg5MWQ2MDdkMjhlZmUxMjA4ZWZjNDNiZWI3MDgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.B83CLM9Tc055wVb_xEp_tfMxv6XXarr2ghf9LfpNdls)

спасибо разобрался, оказывается в Хроме нет колонки ПОСТ, есть в других браузерах. И второй нюанс, только в видеопосте появился кода Авторизэйшн, в фотопостах этого кода нет. Запустилось заработало)

**Comment by vasyan35** [comment]
> ![изображение](https://private-user-images.githubusercontent.com/18719896/397008424-e3f154f1-bd15-4d64-9989-c56d7e0b4725.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NDE3OTIsIm5iZiI6MTczNDU0MTQ5MiwicGF0aCI6Ii8xODcxOTg5Ni8zOTcwMDg0MjQtZTNmMTU0ZjEtYmQxNS00ZDY0LTk5ODktYzU2ZDdlMGI0NzI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDE3MDQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMmJlYTMxMjMxNDk5ZTYwMDMxOTk3M2FkNzRhMDUzZDY4NmE5ZTEzNjllOTA5N2U5MDk1MDU2Y2U1ZmJkNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8tIxSkUH-nyek4umiBsLO37JNnAhUzj2C9xqUwGslnE) нажимаете в браузере F12, выбираете вкладку "сеть" (я пользуюсь FF, в Chrome всё аналогично) и всё.
> 
> на главной boosty заголовка Authorization нет, но вот если зайти на пост с видео — там он появляется.

Спасибо разобрался. Оказывается в Хроме нет колонки ПОСТ, и авторизэйшн код есть только в видеопосте. Вот такой нюанс...

**Comment by lowfc** [comment]
Нужные заголовки можно найти в запросе **post** `https://api.boosty.to/v1/blog/stat/post/`
Если в заголовках этого запроса параметры отсутствуют - скорее всего ваш браузер их закешировал и не отображает. Обновите страницу со сбросом кеша, с помощью `Shift` + `F5` и тогда они появятся.
